log:
  # true: stderr, false: logfiles
  logtostderr: true
  alsologtostderr: false
  colorlogtostderr: true
  # LOG(), 0: INFO, 1: WARNING, 2: ERROR, 3: FATAL
  minloglevel: 0
  # VLOG(N)
  v: 0
  log_prefix: true
  log_dir: "."
  max_log_size: 8
  stop_logging_if_full_disk: true

server:
  host: 127.0.0.1
  port: 8080

  http:
    target: "/streams"
    timeout: 5

  ws:
    target_prefix: "/stream/"
    target_id: "a"

client:
  # dec_name: "h264_cuvid"
  dec_thread_count: 8
  # 1: FF_THREAD_FRAME, 2: FF_THREAD_SLICE
  dec_thread_type: 1

  ui_wait_secs: 10
