log:
  # true: stderr, false: logfiles
  logtostderr: true
  alsologtostderr: false
  colorlogtostderr: true
  # LOG(), 0: INFO, 1: WARNING, 2: ERROR, 3: FATAL
  minloglevel: 0
  # VLOG(N)
  v: 0
  log_prefix: true
  log_dir: "."
  max_log_size: 8
  stop_logging_if_full_disk: true

server:
  addr: "0.0.0.0"
  port: 8080
  threads: 3

  http:
    enable: true
    doc_root: "../ws-wasm-player/"

  cors:
    enabled: true
    allowed_origins: "*"
    allowed_methods: [ GET ]
    allowed_headers:
      - Content-Type
    allowed_credentials: false
    exposed_headers:
      - Content-Type
    debug: false

  stream:
    http_target: "/streams"
    ws_target_prefix: "/stream/"

streams:
  -
    id: "a"
    method: "file"
    input_url: "../data/test.mp4"

    dump_format: false
  -
    id: "b"
    method: "network"
    input_url: "rtsp://127.0.0.1:8554/test"

    max_delay: 1000000
    rtsp_transport: "tcp"
    stimeout: 5000000
  -
    id: "c"
    method: "webcam"
    input_url: "/dev/video0"

    input_format: "v4l2"
    width: 640
    height: 480
    framerate: 20
    pixel_format: "yuyv422"

    filters:
      # - type: "video_bsf"
      - type: "video_enc"
        enc_name: "h264_nvenc"
        enc_bit_rate: 400000
        enc_framerate: 5
        enc_gop_size: 10
        enc_max_b_frames: 0
        enc_qmin: -1
        enc_qmax: -1
        enc_thread_count: -1
        ## ffmpeg -h encoder=h264_nvenc
        enc_open_options:
          preset: "medium"
          zerolatency: "1"
          rc: "vbr"
        ## ffmpeg -h encoder=libx264
        # enc_name: "libx264"
        # enc_open_options:
        #   preset: "medium"
        #   tune: "zerolatency"
        #   nal-hrd: "vbr"
        #   crf: "25"

# 25 = 1000 / 40 fps
stream_get_frequency: 25

# test only: multithreading glfw not coding stable now
stream_ui_enable: false
