log:
  logtostderr: true
  alsologtostderr: false
  colorlogtostderr: true
  minloglevel: 0
  v: 2
  log_prefix: true
  log_dir: "."
  max_log_size: 8
  stop_logging_if_full_disk: true

server:
  addr: "0.0.0.0"
  port: 8080
  threads: 3

  http:
    enable: false
